server:
  port: 8083

spring:
  application:
    name: bookcomposite
  datasource:
    url: mongodb://localhost:27017/bookcomposite
    username: root
    password:
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8087/eureka
